name: Build Docker Image

on:
  workflow_dispatch:
    branches:
      - main

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: docker login
        run: |
          docker login -u yatodak -p ${{ env.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t yatodak/astontbarbay:latest .

      - name: Docker Push
        run: |
          docker push yatodak/astontbarbay:latest
